version: '3'
services:
    mysql:
        image: mysql
        ports:
            - 3306:3306            
        environment: 
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=public
    
    guardian:
        build: 
            context: ./services/guardian
            args: 
                NPM_TOKEN: $NPM_TOKEN
        env_file: .env
        environment: 
            - GUARD_SQL_HOST=guardian_db
        ports: 
            - 8080:8080
            - 9229:9229
        volumes: 
            - ${PWD}/services/guardian:/usr/src/app
            - /usr/src/app/node_modules
        links: 
            - mysql:guardian_db
        depends_on:
            - mysql
