name: CI

on: 
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: npx lerna bootstrap
    - run: npx lerna run build
    - run: npx lerna run test
      env:
        CI: true
