name: CI

on: 
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://npm.pkg.github.com'
        scope: 'guardian'
    - run: npm ci
    - run: npm run build
    - run: npm test
    - name: Git user
      run: |
        git config --global user.name ${GITHUB_ACTOR}
        git config --global user.email ${GITHUB_ACTOR}@github.com
    - run: npm run publish
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
